# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import forgetting_engine_pb2 as forgetting__engine__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in forgetting_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ForgettingEngineStub(object):
    """── 遗忘引擎 gRPC 服务 ──────────────────────────────────

    调用方（如 HuFu Go 服务）通过此接口与引擎交互。
    插件（SkincareAdapter）在引擎启动时注册，调用方无感知。

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAgent = channel.unary_unary(
                '/forgetting_engine.ForgettingEngine/CreateAgent',
                request_serializer=forgetting__engine__pb2.CreateAgentRequest.SerializeToString,
                response_deserializer=forgetting__engine__pb2.CreateAgentResponse.FromString,
                _registered_method=True)
        self.DeleteAgent = channel.unary_unary(
                '/forgetting_engine.ForgettingEngine/DeleteAgent',
                request_serializer=forgetting__engine__pb2.DeleteAgentRequest.SerializeToString,
                response_deserializer=forgetting__engine__pb2.DeleteAgentResponse.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/forgetting_engine.ForgettingEngine/ListAgents',
                request_serializer=forgetting__engine__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=forgetting__engine__pb2.ListAgentsResponse.FromString,
                _registered_method=True)
        self.Ingest = channel.unary_unary(
                '/forgetting_engine.ForgettingEngine/Ingest',
                request_serializer=forgetting__engine__pb2.IngestRequest.SerializeToString,
                response_deserializer=forgetting__engine__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.RetrieveAndRender = channel.unary_unary(
                '/forgetting_engine.ForgettingEngine/RetrieveAndRender',
                request_serializer=forgetting__engine__pb2.RetrieveAndRenderRequest.SerializeToString,
                response_deserializer=forgetting__engine__pb2.RetrieveAndRenderResponse.FromString,
                _registered_method=True)
        self.DecayCycle = channel.unary_unary(
                '/forgetting_engine.ForgettingEngine/DecayCycle',
                request_serializer=forgetting__engine__pb2.DecayCycleRequest.SerializeToString,
                response_deserializer=forgetting__engine__pb2.DecayCycleResponse.FromString,
                _registered_method=True)
        self.GetUsage = channel.unary_unary(
                '/forgetting_engine.ForgettingEngine/GetUsage',
                request_serializer=forgetting__engine__pb2.GetUsageRequest.SerializeToString,
                response_deserializer=forgetting__engine__pb2.GetUsageResponse.FromString,
                _registered_method=True)


class ForgettingEngineServicer(object):
    """── 遗忘引擎 gRPC 服务 ──────────────────────────────────

    调用方（如 HuFu Go 服务）通过此接口与引擎交互。
    插件（SkincareAdapter）在引擎启动时注册，调用方无感知。

    """

    def CreateAgent(self, request, context):
        """── Agent 管理 ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ingest(self, request, context):
        """── 记忆写入 ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveAndRender(self, request, context):
        """── 检索 + 注入（最常用，一次调用完成）──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecayCycle(self, request, context):
        """── 遗忘维护 ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsage(self, request, context):
        """── 计费查询 ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ForgettingEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAgent,
                    request_deserializer=forgetting__engine__pb2.CreateAgentRequest.FromString,
                    response_serializer=forgetting__engine__pb2.CreateAgentResponse.SerializeToString,
            ),
            'DeleteAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAgent,
                    request_deserializer=forgetting__engine__pb2.DeleteAgentRequest.FromString,
                    response_serializer=forgetting__engine__pb2.DeleteAgentResponse.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=forgetting__engine__pb2.ListAgentsRequest.FromString,
                    response_serializer=forgetting__engine__pb2.ListAgentsResponse.SerializeToString,
            ),
            'Ingest': grpc.unary_unary_rpc_method_handler(
                    servicer.Ingest,
                    request_deserializer=forgetting__engine__pb2.IngestRequest.FromString,
                    response_serializer=forgetting__engine__pb2.IngestResponse.SerializeToString,
            ),
            'RetrieveAndRender': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveAndRender,
                    request_deserializer=forgetting__engine__pb2.RetrieveAndRenderRequest.FromString,
                    response_serializer=forgetting__engine__pb2.RetrieveAndRenderResponse.SerializeToString,
            ),
            'DecayCycle': grpc.unary_unary_rpc_method_handler(
                    servicer.DecayCycle,
                    request_deserializer=forgetting__engine__pb2.DecayCycleRequest.FromString,
                    response_serializer=forgetting__engine__pb2.DecayCycleResponse.SerializeToString,
            ),
            'GetUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsage,
                    request_deserializer=forgetting__engine__pb2.GetUsageRequest.FromString,
                    response_serializer=forgetting__engine__pb2.GetUsageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forgetting_engine.ForgettingEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forgetting_engine.ForgettingEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ForgettingEngine(object):
    """── 遗忘引擎 gRPC 服务 ──────────────────────────────────

    调用方（如 HuFu Go 服务）通过此接口与引擎交互。
    插件（SkincareAdapter）在引擎启动时注册，调用方无感知。

    """

    @staticmethod
    def CreateAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgetting_engine.ForgettingEngine/CreateAgent',
            forgetting__engine__pb2.CreateAgentRequest.SerializeToString,
            forgetting__engine__pb2.CreateAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgetting_engine.ForgettingEngine/DeleteAgent',
            forgetting__engine__pb2.DeleteAgentRequest.SerializeToString,
            forgetting__engine__pb2.DeleteAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgetting_engine.ForgettingEngine/ListAgents',
            forgetting__engine__pb2.ListAgentsRequest.SerializeToString,
            forgetting__engine__pb2.ListAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ingest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgetting_engine.ForgettingEngine/Ingest',
            forgetting__engine__pb2.IngestRequest.SerializeToString,
            forgetting__engine__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveAndRender(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgetting_engine.ForgettingEngine/RetrieveAndRender',
            forgetting__engine__pb2.RetrieveAndRenderRequest.SerializeToString,
            forgetting__engine__pb2.RetrieveAndRenderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecayCycle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgetting_engine.ForgettingEngine/DecayCycle',
            forgetting__engine__pb2.DecayCycleRequest.SerializeToString,
            forgetting__engine__pb2.DecayCycleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgetting_engine.ForgettingEngine/GetUsage',
            forgetting__engine__pb2.GetUsageRequest.SerializeToString,
            forgetting__engine__pb2.GetUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
